/**
 * Order numbers (REP-000001) and quote numbers (D-000001) are generated by
 * PostgreSQL sequences (see migrations). This module only validates and
 * normalises user input; it never generates numbers.
 */
export const ORDER_NUMBER_REGEX = /^REP-\d{6,}$/;
export const QUOTE_NUMBER_REGEX = /^D-\d{6,}$/;

export function normalizeOrderNumber(input: string): string | null {
  const cleaned = input.trim().toUpperCase().replace(/\s+/g, "").replace(/^REP-?/, "");
  const withPrefix = /^\d+$/.test(cleaned) ? `REP-${cleaned.padStart(6, "0")}` : `REP-${cleaned}`;
  return ORDER_NUMBER_REGEX.test(withPrefix) ? withPrefix : null;
}

export function isValidOrderNumber(input: string): boolean {
  return ORDER_NUMBER_REGEX.test(input);
}
