-- =============================================================================
-- CATALOGUE DE RÉPARATION — PlayStation 5
--
-- PROVENANCE : contrairement à supabase/catalog-reparations.sql, ce fichier ne
-- vient PAS du document « Liste de réparation » du client — la PS5 n'y figure
-- pas. Les modèles et les pannes ci-dessous sont les pannes courantes de la
-- gamme PlayStation 5, calquées sur la structure retenue pour la PS4 dans le
-- document (mêmes catégories, mêmes formulations), et complétées par ce qui est
-- propre à la PS5 : HDMI 2.1, métal liquide, SSD M.2, lecteur amovible.
--
-- À FAIRE RELIRE PAR L'ATELIER avant mise en ligne : c'est le seul fichier du
-- dépôt dont le contenu ne provient pas du client.
--
-- Aucun tarif n'est importé : comme les 887 prestations du document, chaque
-- ligne arrive à 0 € et « tarif à configurer », donc « sur devis » côté client
-- tant qu'un prix n'a pas été saisi dans Catalogue → Réparations.
--
-- Rejouable : aucune suppression, aucun écrasement de prix.
--
--   psql "$DB_URL" -f supabase/catalog-ps5.sql
-- =============================================================================

set search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Les 5 modèles de la gamme PlayStation 5
-- ---------------------------------------------------------------------------
insert into public.console_models (brand_id, name, slug, short_name, release_year, display_order, family, is_retro, is_handheld, variants, common_issues, is_active)
select b.id, 'PlayStation 5', 'ps5', 'PS5', 2020, 7, 'ps5', false, false,
       array['Standard (CFI-1000 à 1200)', 'avec lecteur Blu-ray']::text[], array['Ne s''allume plus', 'Port HDMI', 'Surchauffe', 'Lecteur Blu-ray']::text[], true
  from public.brands b where b.slug = 'playstation'
on conflict (slug) do nothing;
insert into public.console_models (brand_id, name, slug, short_name, release_year, display_order, family, is_retro, is_handheld, variants, common_issues, is_active)
select b.id, 'PlayStation 5 Digital Edition', 'ps5-digital', 'PS5 Digital', 2020, 8, 'ps5', false, false,
       array['Digital (CFI-1000B à 1200B)', 'sans lecteur']::text[], array['Ne s''allume plus', 'Port HDMI', 'Surchauffe', 'SSD non reconnu']::text[], true
  from public.brands b where b.slug = 'playstation'
on conflict (slug) do nothing;
insert into public.console_models (brand_id, name, slug, short_name, release_year, display_order, family, is_retro, is_handheld, variants, common_issues, is_active)
select b.id, 'PlayStation 5 Slim', 'ps5-slim', 'PS5 Slim', 2023, 9, 'ps5', false, false,
       array['Slim (CFI-2000)', 'lecteur Blu-ray amovible']::text[], array['Ne s''allume plus', 'Port HDMI', 'Lecteur amovible non reconnu']::text[], true
  from public.brands b where b.slug = 'playstation'
on conflict (slug) do nothing;
insert into public.console_models (brand_id, name, slug, short_name, release_year, display_order, family, is_retro, is_handheld, variants, common_issues, is_active)
select b.id, 'PlayStation 5 Slim Digital Edition', 'ps5-slim-digital', 'PS5 Slim Digital', 2023, 10, 'ps5', false, false,
       array['Slim Digital (CFI-2000B)', 'lecteur en option']::text[], array['Ne s''allume plus', 'Port HDMI', 'Surchauffe']::text[], true
  from public.brands b where b.slug = 'playstation'
on conflict (slug) do nothing;
insert into public.console_models (brand_id, name, slug, short_name, release_year, display_order, family, is_retro, is_handheld, variants, common_issues, is_active)
select b.id, 'PlayStation 5 Pro', 'ps5-pro', 'PS5 Pro', 2024, 11, 'ps5', false, false,
       array['Pro (CFI-7000)', 'lecteur en option']::text[], array['Surchauffe', 'Port HDMI', 'Ventilateur bruyant']::text[], true
  from public.brands b where b.slug = 'playstation'
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- Pannes absentes du catalogue (les autres sont déjà créées par le document)
-- ---------------------------------------------------------------------------
insert into public.faults (name, slug, display_order) values
  ('Base de données corrompue', 'base-de-donnees-corrompue', 10000),
  ('Bruit anormal du lecteur', 'bruit-anormal-du-lecteur', 10010),
  ('Connecteur du lecteur amovible endommagé', 'connecteur-du-lecteur-amovible-endommage', 10020),
  ('Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 10030),
  ('Console qui se fige', 'console-qui-se-fige', 10040),
  ('Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 10050),
  ('HDR indisponible', 'hdr-indisponible', 10060),
  ('Lecteur amovible non reconnu', 'lecteur-amovible-non-reconnu', 10070),
  ('Métal liquide dégradé', 'metal-liquide-degrade', 10080),
  ('Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 10090),
  ('PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 10100),
  ('PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 10110),
  ('PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 10120),
  ('Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 10130),
  ('Remplacement du SSD', 'remplacement-du-ssd', 10140),
  ('SSD non reconnu', 'ssd-non-reconnu', 10150),
  ('Sortie de veille impossible', 'sortie-de-veille-impossible', 10160),
  ('Trois bips puis extinction', 'trois-bips-et-extinction', 10170),
  ('Voyant blanc clignotant', 'voyant-blanc-clignotant', 10180)
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- Prestations : modèle → catégorie → panne
-- ---------------------------------------------------------------------------
with source (model_slug, category_slug, fault_slug, name, slug, display_order) as (values
  ('ps5', 'image-et-hdmi', 'changement-du-port-hdmi', 'Changement du port HDMI', 'changement-du-port-hdmi', 10),
  ('ps5', 'image-et-hdmi', 'port-hdmi-endommage', 'Port HDMI endommagé', 'port-hdmi-endommage', 20),
  ('ps5', 'image-et-hdmi', 'aucun-signal-hdmi', 'Aucun signal HDMI', 'aucun-signal-hdmi', 30),
  ('ps5', 'image-et-hdmi', 'ecran-noir-image-et-hdmi', 'Écran noir', 'ecran-noir-image-et-hdmi', 40),
  ('ps5', 'image-et-hdmi', 'pas-dimage', 'Pas d’image', 'pas-dimage', 50),
  ('ps5', 'image-et-hdmi', 'image-qui-coupe', 'Image qui coupe', 'image-qui-coupe', 60),
  ('ps5', 'image-et-hdmi', 'image-instable', 'Image instable', 'image-instable', 70),
  ('ps5', 'image-et-hdmi', 'image-deformee', 'Image déformée', 'image-deformee', 80),
  ('ps5', 'image-et-hdmi', 'defauts-graphiques-artefacts', 'Défauts graphiques / artefacts', 'defauts-graphiques-artefacts', 90),
  ('ps5', 'image-et-hdmi', 'probleme-de-resolution', 'Problème de résolution', 'probleme-de-resolution', 100),
  ('ps5', 'image-et-hdmi', 'probleme-de-sortie-video', 'Problème de sortie vidéo', 'probleme-de-sortie-video', 110),
  ('ps5', 'image-et-hdmi', 'pas-de-4k-120-hz', 'Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 120),
  ('ps5', 'image-et-hdmi', 'hdr-indisponible', 'HDR indisponible', 'hdr-indisponible', 130),
  ('ps5', 'allumage-et-alimentation', 'ps5-qui-ne-sallume-plus', 'PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 140),
  ('ps5', 'allumage-et-alimentation', 'ps5-qui-seteint-immediatement', 'PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 150),
  ('ps5', 'allumage-et-alimentation', 'ps5-qui-seteint-toute-seule', 'PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 160),
  ('ps5', 'allumage-et-alimentation', 'voyant-blanc-clignotant', 'Voyant blanc clignotant', 'voyant-blanc-clignotant', 170),
  ('ps5', 'allumage-et-alimentation', 'trois-bips-et-extinction', 'Trois bips puis extinction', 'trois-bips-et-extinction', 180),
  ('ps5', 'allumage-et-alimentation', 'probleme-dalimentation', 'Problème d’alimentation', 'probleme-dalimentation', 190),
  ('ps5', 'allumage-et-alimentation', 'bloc-dalimentation-defectueux', 'Bloc d’alimentation défectueux', 'bloc-dalimentation-defectueux', 200),
  ('ps5', 'allumage-et-alimentation', 'connecteur-dalimentation-endommage', 'Connecteur d’alimentation endommagé', 'connecteur-dalimentation-endommage', 210),
  ('ps5', 'allumage-et-alimentation', 'court-circuit', 'Court-circuit', 'court-circuit', 220),
  ('ps5', 'allumage-et-alimentation', 'sortie-de-veille-impossible', 'Sortie de veille impossible', 'sortie-de-veille-impossible', 230),
  ('ps5', 'lecteur-blu-ray', 'lecteur-blu-ray-defectueux', 'Lecteur Blu-ray défectueux', 'lecteur-blu-ray-defectueux', 240),
  ('ps5', 'lecteur-blu-ray', 'disque-non-reconnu', 'Disque non reconnu', 'disque-non-reconnu', 250),
  ('ps5', 'lecteur-blu-ray', 'disque-qui-ne-rentre-pas', 'Disque qui ne rentre pas', 'disque-qui-ne-rentre-pas', 260),
  ('ps5', 'lecteur-blu-ray', 'disque-qui-reste-bloque', 'Disque qui reste bloqué', 'disque-qui-reste-bloque', 270),
  ('ps5', 'lecteur-blu-ray', 'disque-qui-ne-sejecte-pas', 'Disque qui ne s’éjecte pas', 'disque-qui-ne-sejecte-pas', 280),
  ('ps5', 'lecteur-blu-ray', 'ejection-automatique-du-disque', 'Éjection automatique du disque', 'ejection-automatique-du-disque', 290),
  ('ps5', 'lecteur-blu-ray', 'mecanisme-du-lecteur-defectueux', 'Mécanisme du lecteur défectueux', 'mecanisme-du-lecteur-defectueux', 300),
  ('ps5', 'lecteur-blu-ray', 'bruit-anormal-du-lecteur', 'Bruit anormal du lecteur', 'bruit-anormal-du-lecteur', 310),
  ('ps5', 'ssd-et-stockage', 'ssd-interne-defectueux', 'SSD interne défectueux', 'ssd-interne-defectueux', 320),
  ('ps5', 'ssd-et-stockage', 'ssd-non-reconnu', 'SSD non reconnu', 'ssd-non-reconnu', 330),
  ('ps5', 'ssd-et-stockage', 'remplacement-du-ssd', 'Remplacement du SSD', 'remplacement-du-ssd', 340),
  ('ps5', 'ssd-et-stockage', 'extension-ssd-m-2-non-reconnue', 'Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 350),
  ('ps5', 'ssd-et-stockage', 'erreur-de-stockage-externe', 'Erreur de stockage externe', 'erreur-de-stockage-externe', 360),
  ('ps5', 'ssd-et-stockage', 'console-bloquee-au-demarrage-ssd-et-stockage', 'Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 370),
  ('ps5', 'systeme', 'erreur-du-logiciel-systeme', 'Erreur du logiciel système', 'erreur-du-logiciel-systeme', 380),
  ('ps5', 'systeme', 'mise-a-jour-impossible', 'Mise à jour impossible', 'mise-a-jour-impossible', 390),
  ('ps5', 'systeme', 'reinstallation-systeme-impossible', 'Réinstallation système impossible', 'reinstallation-systeme-impossible', 400),
  ('ps5', 'systeme', 'boucle-du-mode-sans-echec', 'Boucle du mode sans échec', 'boucle-du-mode-sans-echec', 410),
  ('ps5', 'systeme', 'base-de-donnees-corrompue', 'Base de données corrompue', 'base-de-donnees-corrompue', 420),
  ('ps5', 'systeme', 'console-qui-se-fige', 'Console qui se fige', 'console-qui-se-fige', 430),
  ('ps5', 'refroidissement', 'surchauffe', 'Surchauffe', 'surchauffe', 440),
  ('ps5', 'refroidissement', 'ventilateur-bruyant', 'Ventilateur bruyant', 'ventilateur-bruyant', 450),
  ('ps5', 'refroidissement', 'ventilateur-defectueux', 'Ventilateur défectueux', 'ventilateur-defectueux', 460),
  ('ps5', 'refroidissement', 'console-qui-chauffe-anormalement', 'Console qui chauffe anormalement', 'console-qui-chauffe-anormalement', 470),
  ('ps5', 'refroidissement', 'metal-liquide-degrade', 'Métal liquide dégradé', 'metal-liquide-degrade', 480),
  ('ps5', 'refroidissement', 'nettoyage-et-depoussierage', 'Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 490),
  ('ps5', 'usb-et-manette', 'port-usb-defectueux', 'Port USB défectueux', 'port-usb-defectueux', 500),
  ('ps5', 'usb-et-manette', 'port-usb-endommage', 'Port USB endommagé', 'port-usb-endommage', 510),
  ('ps5', 'usb-et-manette', 'port-usb-c-endommage', 'Port USB-C endommagé', 'port-usb-c-endommage', 520),
  ('ps5', 'usb-et-manette', 'manette-non-reconnue', 'Manette non reconnue', 'manette-non-reconnue', 530),
  ('ps5', 'usb-et-manette', 'manette-qui-ne-se-connecte-pas', 'Manette qui ne se connecte pas', 'manette-qui-ne-se-connecte-pas', 540),
  ('ps5', 'usb-et-manette', 'manette-qui-ne-charge-pas', 'Manette qui ne charge pas', 'manette-qui-ne-charge-pas', 550),
  ('ps5', 'usb-et-manette', 'probleme-de-synchronisation', 'Problème de synchronisation', 'probleme-de-synchronisation', 560),
  ('ps5', 'usb-et-manette', 'joystick-drift', 'Joystick drift', 'joystick-drift', 570),
  ('ps5', 'usb-et-manette', 'gachette-defectueuse', 'Gâchette défectueuse', 'gachette-defectueuse', 580),
  ('ps5', 'connexion', 'wi-fi-defectueux', 'Wi-Fi défectueux', 'wi-fi-defectueux', 590),
  ('ps5', 'connexion', 'bluetooth-defectueux', 'Bluetooth défectueux', 'bluetooth-defectueux', 600),
  ('ps5', 'connexion', 'wi-fi-non-detecte', 'Wi-Fi non détecté', 'wi-fi-non-detecte', 610),
  ('ps5', 'connexion', 'deconnexions-wi-fi', 'Déconnexions Wi-Fi', 'deconnexions-wi-fi', 620),
  ('ps5', 'connexion', 'probleme-de-connexion-internet', 'Problème de connexion Internet', 'probleme-de-connexion-internet', 630),
  ('ps5', 'connexion', 'ethernet-hs', 'Ethernet HS', 'ethernet-hs', 640),
  ('ps5-digital', 'image-et-hdmi', 'changement-du-port-hdmi', 'Changement du port HDMI', 'changement-du-port-hdmi', 10),
  ('ps5-digital', 'image-et-hdmi', 'port-hdmi-endommage', 'Port HDMI endommagé', 'port-hdmi-endommage', 20),
  ('ps5-digital', 'image-et-hdmi', 'aucun-signal-hdmi', 'Aucun signal HDMI', 'aucun-signal-hdmi', 30),
  ('ps5-digital', 'image-et-hdmi', 'ecran-noir-image-et-hdmi', 'Écran noir', 'ecran-noir-image-et-hdmi', 40),
  ('ps5-digital', 'image-et-hdmi', 'pas-dimage', 'Pas d’image', 'pas-dimage', 50),
  ('ps5-digital', 'image-et-hdmi', 'image-qui-coupe', 'Image qui coupe', 'image-qui-coupe', 60),
  ('ps5-digital', 'image-et-hdmi', 'image-instable', 'Image instable', 'image-instable', 70),
  ('ps5-digital', 'image-et-hdmi', 'image-deformee', 'Image déformée', 'image-deformee', 80),
  ('ps5-digital', 'image-et-hdmi', 'defauts-graphiques-artefacts', 'Défauts graphiques / artefacts', 'defauts-graphiques-artefacts', 90),
  ('ps5-digital', 'image-et-hdmi', 'probleme-de-resolution', 'Problème de résolution', 'probleme-de-resolution', 100),
  ('ps5-digital', 'image-et-hdmi', 'probleme-de-sortie-video', 'Problème de sortie vidéo', 'probleme-de-sortie-video', 110),
  ('ps5-digital', 'image-et-hdmi', 'pas-de-4k-120-hz', 'Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 120),
  ('ps5-digital', 'image-et-hdmi', 'hdr-indisponible', 'HDR indisponible', 'hdr-indisponible', 130),
  ('ps5-digital', 'allumage-et-alimentation', 'ps5-qui-ne-sallume-plus', 'PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 140),
  ('ps5-digital', 'allumage-et-alimentation', 'ps5-qui-seteint-immediatement', 'PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 150),
  ('ps5-digital', 'allumage-et-alimentation', 'ps5-qui-seteint-toute-seule', 'PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 160),
  ('ps5-digital', 'allumage-et-alimentation', 'voyant-blanc-clignotant', 'Voyant blanc clignotant', 'voyant-blanc-clignotant', 170),
  ('ps5-digital', 'allumage-et-alimentation', 'trois-bips-et-extinction', 'Trois bips puis extinction', 'trois-bips-et-extinction', 180),
  ('ps5-digital', 'allumage-et-alimentation', 'probleme-dalimentation', 'Problème d’alimentation', 'probleme-dalimentation', 190),
  ('ps5-digital', 'allumage-et-alimentation', 'bloc-dalimentation-defectueux', 'Bloc d’alimentation défectueux', 'bloc-dalimentation-defectueux', 200),
  ('ps5-digital', 'allumage-et-alimentation', 'connecteur-dalimentation-endommage', 'Connecteur d’alimentation endommagé', 'connecteur-dalimentation-endommage', 210),
  ('ps5-digital', 'allumage-et-alimentation', 'court-circuit', 'Court-circuit', 'court-circuit', 220),
  ('ps5-digital', 'allumage-et-alimentation', 'sortie-de-veille-impossible', 'Sortie de veille impossible', 'sortie-de-veille-impossible', 230),
  ('ps5-digital', 'ssd-et-stockage', 'ssd-interne-defectueux', 'SSD interne défectueux', 'ssd-interne-defectueux', 240),
  ('ps5-digital', 'ssd-et-stockage', 'ssd-non-reconnu', 'SSD non reconnu', 'ssd-non-reconnu', 250),
  ('ps5-digital', 'ssd-et-stockage', 'remplacement-du-ssd', 'Remplacement du SSD', 'remplacement-du-ssd', 260),
  ('ps5-digital', 'ssd-et-stockage', 'extension-ssd-m-2-non-reconnue', 'Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 270),
  ('ps5-digital', 'ssd-et-stockage', 'erreur-de-stockage-externe', 'Erreur de stockage externe', 'erreur-de-stockage-externe', 280),
  ('ps5-digital', 'ssd-et-stockage', 'console-bloquee-au-demarrage-ssd-et-stockage', 'Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 290),
  ('ps5-digital', 'systeme', 'erreur-du-logiciel-systeme', 'Erreur du logiciel système', 'erreur-du-logiciel-systeme', 300),
  ('ps5-digital', 'systeme', 'mise-a-jour-impossible', 'Mise à jour impossible', 'mise-a-jour-impossible', 310),
  ('ps5-digital', 'systeme', 'reinstallation-systeme-impossible', 'Réinstallation système impossible', 'reinstallation-systeme-impossible', 320),
  ('ps5-digital', 'systeme', 'boucle-du-mode-sans-echec', 'Boucle du mode sans échec', 'boucle-du-mode-sans-echec', 330),
  ('ps5-digital', 'systeme', 'base-de-donnees-corrompue', 'Base de données corrompue', 'base-de-donnees-corrompue', 340),
  ('ps5-digital', 'systeme', 'console-qui-se-fige', 'Console qui se fige', 'console-qui-se-fige', 350),
  ('ps5-digital', 'refroidissement', 'surchauffe', 'Surchauffe', 'surchauffe', 360),
  ('ps5-digital', 'refroidissement', 'ventilateur-bruyant', 'Ventilateur bruyant', 'ventilateur-bruyant', 370),
  ('ps5-digital', 'refroidissement', 'ventilateur-defectueux', 'Ventilateur défectueux', 'ventilateur-defectueux', 380),
  ('ps5-digital', 'refroidissement', 'console-qui-chauffe-anormalement', 'Console qui chauffe anormalement', 'console-qui-chauffe-anormalement', 390),
  ('ps5-digital', 'refroidissement', 'metal-liquide-degrade', 'Métal liquide dégradé', 'metal-liquide-degrade', 400),
  ('ps5-digital', 'refroidissement', 'nettoyage-et-depoussierage', 'Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 410),
  ('ps5-digital', 'usb-et-manette', 'port-usb-defectueux', 'Port USB défectueux', 'port-usb-defectueux', 420),
  ('ps5-digital', 'usb-et-manette', 'port-usb-endommage', 'Port USB endommagé', 'port-usb-endommage', 430),
  ('ps5-digital', 'usb-et-manette', 'port-usb-c-endommage', 'Port USB-C endommagé', 'port-usb-c-endommage', 440),
  ('ps5-digital', 'usb-et-manette', 'manette-non-reconnue', 'Manette non reconnue', 'manette-non-reconnue', 450),
  ('ps5-digital', 'usb-et-manette', 'manette-qui-ne-se-connecte-pas', 'Manette qui ne se connecte pas', 'manette-qui-ne-se-connecte-pas', 460),
  ('ps5-digital', 'usb-et-manette', 'manette-qui-ne-charge-pas', 'Manette qui ne charge pas', 'manette-qui-ne-charge-pas', 470),
  ('ps5-digital', 'usb-et-manette', 'probleme-de-synchronisation', 'Problème de synchronisation', 'probleme-de-synchronisation', 480),
  ('ps5-digital', 'usb-et-manette', 'joystick-drift', 'Joystick drift', 'joystick-drift', 490),
  ('ps5-digital', 'usb-et-manette', 'gachette-defectueuse', 'Gâchette défectueuse', 'gachette-defectueuse', 500),
  ('ps5-digital', 'connexion', 'wi-fi-defectueux', 'Wi-Fi défectueux', 'wi-fi-defectueux', 510),
  ('ps5-digital', 'connexion', 'bluetooth-defectueux', 'Bluetooth défectueux', 'bluetooth-defectueux', 520),
  ('ps5-digital', 'connexion', 'wi-fi-non-detecte', 'Wi-Fi non détecté', 'wi-fi-non-detecte', 530),
  ('ps5-digital', 'connexion', 'deconnexions-wi-fi', 'Déconnexions Wi-Fi', 'deconnexions-wi-fi', 540),
  ('ps5-digital', 'connexion', 'probleme-de-connexion-internet', 'Problème de connexion Internet', 'probleme-de-connexion-internet', 550),
  ('ps5-digital', 'connexion', 'ethernet-hs', 'Ethernet HS', 'ethernet-hs', 560),
  ('ps5-slim', 'image-et-hdmi', 'changement-du-port-hdmi', 'Changement du port HDMI', 'changement-du-port-hdmi', 10),
  ('ps5-slim', 'image-et-hdmi', 'port-hdmi-endommage', 'Port HDMI endommagé', 'port-hdmi-endommage', 20),
  ('ps5-slim', 'image-et-hdmi', 'aucun-signal-hdmi', 'Aucun signal HDMI', 'aucun-signal-hdmi', 30),
  ('ps5-slim', 'image-et-hdmi', 'ecran-noir-image-et-hdmi', 'Écran noir', 'ecran-noir-image-et-hdmi', 40),
  ('ps5-slim', 'image-et-hdmi', 'pas-dimage', 'Pas d’image', 'pas-dimage', 50),
  ('ps5-slim', 'image-et-hdmi', 'image-qui-coupe', 'Image qui coupe', 'image-qui-coupe', 60),
  ('ps5-slim', 'image-et-hdmi', 'image-instable', 'Image instable', 'image-instable', 70),
  ('ps5-slim', 'image-et-hdmi', 'image-deformee', 'Image déformée', 'image-deformee', 80),
  ('ps5-slim', 'image-et-hdmi', 'defauts-graphiques-artefacts', 'Défauts graphiques / artefacts', 'defauts-graphiques-artefacts', 90),
  ('ps5-slim', 'image-et-hdmi', 'probleme-de-resolution', 'Problème de résolution', 'probleme-de-resolution', 100),
  ('ps5-slim', 'image-et-hdmi', 'probleme-de-sortie-video', 'Problème de sortie vidéo', 'probleme-de-sortie-video', 110),
  ('ps5-slim', 'image-et-hdmi', 'pas-de-4k-120-hz', 'Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 120),
  ('ps5-slim', 'image-et-hdmi', 'hdr-indisponible', 'HDR indisponible', 'hdr-indisponible', 130),
  ('ps5-slim', 'allumage-et-alimentation', 'ps5-qui-ne-sallume-plus', 'PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 140),
  ('ps5-slim', 'allumage-et-alimentation', 'ps5-qui-seteint-immediatement', 'PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 150),
  ('ps5-slim', 'allumage-et-alimentation', 'ps5-qui-seteint-toute-seule', 'PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 160),
  ('ps5-slim', 'allumage-et-alimentation', 'voyant-blanc-clignotant', 'Voyant blanc clignotant', 'voyant-blanc-clignotant', 170),
  ('ps5-slim', 'allumage-et-alimentation', 'trois-bips-et-extinction', 'Trois bips puis extinction', 'trois-bips-et-extinction', 180),
  ('ps5-slim', 'allumage-et-alimentation', 'probleme-dalimentation', 'Problème d’alimentation', 'probleme-dalimentation', 190),
  ('ps5-slim', 'allumage-et-alimentation', 'bloc-dalimentation-defectueux', 'Bloc d’alimentation défectueux', 'bloc-dalimentation-defectueux', 200),
  ('ps5-slim', 'allumage-et-alimentation', 'connecteur-dalimentation-endommage', 'Connecteur d’alimentation endommagé', 'connecteur-dalimentation-endommage', 210),
  ('ps5-slim', 'allumage-et-alimentation', 'court-circuit', 'Court-circuit', 'court-circuit', 220),
  ('ps5-slim', 'allumage-et-alimentation', 'sortie-de-veille-impossible', 'Sortie de veille impossible', 'sortie-de-veille-impossible', 230),
  ('ps5-slim', 'lecteur-blu-ray', 'lecteur-blu-ray-defectueux', 'Lecteur Blu-ray défectueux', 'lecteur-blu-ray-defectueux', 240),
  ('ps5-slim', 'lecteur-blu-ray', 'disque-non-reconnu', 'Disque non reconnu', 'disque-non-reconnu', 250),
  ('ps5-slim', 'lecteur-blu-ray', 'disque-qui-ne-rentre-pas', 'Disque qui ne rentre pas', 'disque-qui-ne-rentre-pas', 260),
  ('ps5-slim', 'lecteur-blu-ray', 'disque-qui-reste-bloque', 'Disque qui reste bloqué', 'disque-qui-reste-bloque', 270),
  ('ps5-slim', 'lecteur-blu-ray', 'disque-qui-ne-sejecte-pas', 'Disque qui ne s’éjecte pas', 'disque-qui-ne-sejecte-pas', 280),
  ('ps5-slim', 'lecteur-blu-ray', 'ejection-automatique-du-disque', 'Éjection automatique du disque', 'ejection-automatique-du-disque', 290),
  ('ps5-slim', 'lecteur-blu-ray', 'mecanisme-du-lecteur-defectueux', 'Mécanisme du lecteur défectueux', 'mecanisme-du-lecteur-defectueux', 300),
  ('ps5-slim', 'lecteur-blu-ray', 'bruit-anormal-du-lecteur', 'Bruit anormal du lecteur', 'bruit-anormal-du-lecteur', 310),
  ('ps5-slim', 'lecteur-blu-ray', 'lecteur-amovible-non-reconnu', 'Lecteur amovible non reconnu', 'lecteur-amovible-non-reconnu', 320),
  ('ps5-slim', 'lecteur-blu-ray', 'connecteur-du-lecteur-amovible-endommage', 'Connecteur du lecteur amovible endommagé', 'connecteur-du-lecteur-amovible-endommage', 330),
  ('ps5-slim', 'ssd-et-stockage', 'ssd-interne-defectueux', 'SSD interne défectueux', 'ssd-interne-defectueux', 340),
  ('ps5-slim', 'ssd-et-stockage', 'ssd-non-reconnu', 'SSD non reconnu', 'ssd-non-reconnu', 350),
  ('ps5-slim', 'ssd-et-stockage', 'remplacement-du-ssd', 'Remplacement du SSD', 'remplacement-du-ssd', 360),
  ('ps5-slim', 'ssd-et-stockage', 'extension-ssd-m-2-non-reconnue', 'Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 370),
  ('ps5-slim', 'ssd-et-stockage', 'erreur-de-stockage-externe', 'Erreur de stockage externe', 'erreur-de-stockage-externe', 380),
  ('ps5-slim', 'ssd-et-stockage', 'console-bloquee-au-demarrage-ssd-et-stockage', 'Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 390),
  ('ps5-slim', 'systeme', 'erreur-du-logiciel-systeme', 'Erreur du logiciel système', 'erreur-du-logiciel-systeme', 400),
  ('ps5-slim', 'systeme', 'mise-a-jour-impossible', 'Mise à jour impossible', 'mise-a-jour-impossible', 410),
  ('ps5-slim', 'systeme', 'reinstallation-systeme-impossible', 'Réinstallation système impossible', 'reinstallation-systeme-impossible', 420),
  ('ps5-slim', 'systeme', 'boucle-du-mode-sans-echec', 'Boucle du mode sans échec', 'boucle-du-mode-sans-echec', 430),
  ('ps5-slim', 'systeme', 'base-de-donnees-corrompue', 'Base de données corrompue', 'base-de-donnees-corrompue', 440),
  ('ps5-slim', 'systeme', 'console-qui-se-fige', 'Console qui se fige', 'console-qui-se-fige', 450),
  ('ps5-slim', 'refroidissement', 'surchauffe', 'Surchauffe', 'surchauffe', 460),
  ('ps5-slim', 'refroidissement', 'ventilateur-bruyant', 'Ventilateur bruyant', 'ventilateur-bruyant', 470),
  ('ps5-slim', 'refroidissement', 'ventilateur-defectueux', 'Ventilateur défectueux', 'ventilateur-defectueux', 480),
  ('ps5-slim', 'refroidissement', 'console-qui-chauffe-anormalement', 'Console qui chauffe anormalement', 'console-qui-chauffe-anormalement', 490),
  ('ps5-slim', 'refroidissement', 'metal-liquide-degrade', 'Métal liquide dégradé', 'metal-liquide-degrade', 500),
  ('ps5-slim', 'refroidissement', 'nettoyage-et-depoussierage', 'Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 510),
  ('ps5-slim', 'usb-et-manette', 'port-usb-defectueux', 'Port USB défectueux', 'port-usb-defectueux', 520),
  ('ps5-slim', 'usb-et-manette', 'port-usb-endommage', 'Port USB endommagé', 'port-usb-endommage', 530),
  ('ps5-slim', 'usb-et-manette', 'port-usb-c-endommage', 'Port USB-C endommagé', 'port-usb-c-endommage', 540),
  ('ps5-slim', 'usb-et-manette', 'manette-non-reconnue', 'Manette non reconnue', 'manette-non-reconnue', 550),
  ('ps5-slim', 'usb-et-manette', 'manette-qui-ne-se-connecte-pas', 'Manette qui ne se connecte pas', 'manette-qui-ne-se-connecte-pas', 560),
  ('ps5-slim', 'usb-et-manette', 'manette-qui-ne-charge-pas', 'Manette qui ne charge pas', 'manette-qui-ne-charge-pas', 570),
  ('ps5-slim', 'usb-et-manette', 'probleme-de-synchronisation', 'Problème de synchronisation', 'probleme-de-synchronisation', 580),
  ('ps5-slim', 'usb-et-manette', 'joystick-drift', 'Joystick drift', 'joystick-drift', 590),
  ('ps5-slim', 'usb-et-manette', 'gachette-defectueuse', 'Gâchette défectueuse', 'gachette-defectueuse', 600),
  ('ps5-slim', 'connexion', 'wi-fi-defectueux', 'Wi-Fi défectueux', 'wi-fi-defectueux', 610),
  ('ps5-slim', 'connexion', 'bluetooth-defectueux', 'Bluetooth défectueux', 'bluetooth-defectueux', 620),
  ('ps5-slim', 'connexion', 'wi-fi-non-detecte', 'Wi-Fi non détecté', 'wi-fi-non-detecte', 630),
  ('ps5-slim', 'connexion', 'deconnexions-wi-fi', 'Déconnexions Wi-Fi', 'deconnexions-wi-fi', 640),
  ('ps5-slim', 'connexion', 'probleme-de-connexion-internet', 'Problème de connexion Internet', 'probleme-de-connexion-internet', 650),
  ('ps5-slim', 'connexion', 'ethernet-hs', 'Ethernet HS', 'ethernet-hs', 660),
  ('ps5-slim-digital', 'image-et-hdmi', 'changement-du-port-hdmi', 'Changement du port HDMI', 'changement-du-port-hdmi', 10),
  ('ps5-slim-digital', 'image-et-hdmi', 'port-hdmi-endommage', 'Port HDMI endommagé', 'port-hdmi-endommage', 20),
  ('ps5-slim-digital', 'image-et-hdmi', 'aucun-signal-hdmi', 'Aucun signal HDMI', 'aucun-signal-hdmi', 30),
  ('ps5-slim-digital', 'image-et-hdmi', 'ecran-noir-image-et-hdmi', 'Écran noir', 'ecran-noir-image-et-hdmi', 40),
  ('ps5-slim-digital', 'image-et-hdmi', 'pas-dimage', 'Pas d’image', 'pas-dimage', 50),
  ('ps5-slim-digital', 'image-et-hdmi', 'image-qui-coupe', 'Image qui coupe', 'image-qui-coupe', 60),
  ('ps5-slim-digital', 'image-et-hdmi', 'image-instable', 'Image instable', 'image-instable', 70),
  ('ps5-slim-digital', 'image-et-hdmi', 'image-deformee', 'Image déformée', 'image-deformee', 80),
  ('ps5-slim-digital', 'image-et-hdmi', 'defauts-graphiques-artefacts', 'Défauts graphiques / artefacts', 'defauts-graphiques-artefacts', 90),
  ('ps5-slim-digital', 'image-et-hdmi', 'probleme-de-resolution', 'Problème de résolution', 'probleme-de-resolution', 100),
  ('ps5-slim-digital', 'image-et-hdmi', 'probleme-de-sortie-video', 'Problème de sortie vidéo', 'probleme-de-sortie-video', 110),
  ('ps5-slim-digital', 'image-et-hdmi', 'pas-de-4k-120-hz', 'Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 120),
  ('ps5-slim-digital', 'image-et-hdmi', 'hdr-indisponible', 'HDR indisponible', 'hdr-indisponible', 130),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'ps5-qui-ne-sallume-plus', 'PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 140),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'ps5-qui-seteint-immediatement', 'PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 150),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'ps5-qui-seteint-toute-seule', 'PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 160),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'voyant-blanc-clignotant', 'Voyant blanc clignotant', 'voyant-blanc-clignotant', 170),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'trois-bips-et-extinction', 'Trois bips puis extinction', 'trois-bips-et-extinction', 180),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'probleme-dalimentation', 'Problème d’alimentation', 'probleme-dalimentation', 190),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'bloc-dalimentation-defectueux', 'Bloc d’alimentation défectueux', 'bloc-dalimentation-defectueux', 200),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'connecteur-dalimentation-endommage', 'Connecteur d’alimentation endommagé', 'connecteur-dalimentation-endommage', 210),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'court-circuit', 'Court-circuit', 'court-circuit', 220),
  ('ps5-slim-digital', 'allumage-et-alimentation', 'sortie-de-veille-impossible', 'Sortie de veille impossible', 'sortie-de-veille-impossible', 230),
  ('ps5-slim-digital', 'lecteur-blu-ray', 'lecteur-amovible-non-reconnu', 'Lecteur amovible non reconnu', 'lecteur-amovible-non-reconnu', 240),
  ('ps5-slim-digital', 'lecteur-blu-ray', 'connecteur-du-lecteur-amovible-endommage', 'Connecteur du lecteur amovible endommagé', 'connecteur-du-lecteur-amovible-endommage', 250),
  ('ps5-slim-digital', 'ssd-et-stockage', 'ssd-interne-defectueux', 'SSD interne défectueux', 'ssd-interne-defectueux', 260),
  ('ps5-slim-digital', 'ssd-et-stockage', 'ssd-non-reconnu', 'SSD non reconnu', 'ssd-non-reconnu', 270),
  ('ps5-slim-digital', 'ssd-et-stockage', 'remplacement-du-ssd', 'Remplacement du SSD', 'remplacement-du-ssd', 280),
  ('ps5-slim-digital', 'ssd-et-stockage', 'extension-ssd-m-2-non-reconnue', 'Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 290),
  ('ps5-slim-digital', 'ssd-et-stockage', 'erreur-de-stockage-externe', 'Erreur de stockage externe', 'erreur-de-stockage-externe', 300),
  ('ps5-slim-digital', 'ssd-et-stockage', 'console-bloquee-au-demarrage-ssd-et-stockage', 'Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 310),
  ('ps5-slim-digital', 'systeme', 'erreur-du-logiciel-systeme', 'Erreur du logiciel système', 'erreur-du-logiciel-systeme', 320),
  ('ps5-slim-digital', 'systeme', 'mise-a-jour-impossible', 'Mise à jour impossible', 'mise-a-jour-impossible', 330),
  ('ps5-slim-digital', 'systeme', 'reinstallation-systeme-impossible', 'Réinstallation système impossible', 'reinstallation-systeme-impossible', 340),
  ('ps5-slim-digital', 'systeme', 'boucle-du-mode-sans-echec', 'Boucle du mode sans échec', 'boucle-du-mode-sans-echec', 350),
  ('ps5-slim-digital', 'systeme', 'base-de-donnees-corrompue', 'Base de données corrompue', 'base-de-donnees-corrompue', 360),
  ('ps5-slim-digital', 'systeme', 'console-qui-se-fige', 'Console qui se fige', 'console-qui-se-fige', 370),
  ('ps5-slim-digital', 'refroidissement', 'surchauffe', 'Surchauffe', 'surchauffe', 380),
  ('ps5-slim-digital', 'refroidissement', 'ventilateur-bruyant', 'Ventilateur bruyant', 'ventilateur-bruyant', 390),
  ('ps5-slim-digital', 'refroidissement', 'ventilateur-defectueux', 'Ventilateur défectueux', 'ventilateur-defectueux', 400),
  ('ps5-slim-digital', 'refroidissement', 'console-qui-chauffe-anormalement', 'Console qui chauffe anormalement', 'console-qui-chauffe-anormalement', 410),
  ('ps5-slim-digital', 'refroidissement', 'metal-liquide-degrade', 'Métal liquide dégradé', 'metal-liquide-degrade', 420),
  ('ps5-slim-digital', 'refroidissement', 'nettoyage-et-depoussierage', 'Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 430),
  ('ps5-slim-digital', 'usb-et-manette', 'port-usb-defectueux', 'Port USB défectueux', 'port-usb-defectueux', 440),
  ('ps5-slim-digital', 'usb-et-manette', 'port-usb-endommage', 'Port USB endommagé', 'port-usb-endommage', 450),
  ('ps5-slim-digital', 'usb-et-manette', 'port-usb-c-endommage', 'Port USB-C endommagé', 'port-usb-c-endommage', 460),
  ('ps5-slim-digital', 'usb-et-manette', 'manette-non-reconnue', 'Manette non reconnue', 'manette-non-reconnue', 470),
  ('ps5-slim-digital', 'usb-et-manette', 'manette-qui-ne-se-connecte-pas', 'Manette qui ne se connecte pas', 'manette-qui-ne-se-connecte-pas', 480),
  ('ps5-slim-digital', 'usb-et-manette', 'manette-qui-ne-charge-pas', 'Manette qui ne charge pas', 'manette-qui-ne-charge-pas', 490),
  ('ps5-slim-digital', 'usb-et-manette', 'probleme-de-synchronisation', 'Problème de synchronisation', 'probleme-de-synchronisation', 500),
  ('ps5-slim-digital', 'usb-et-manette', 'joystick-drift', 'Joystick drift', 'joystick-drift', 510),
  ('ps5-slim-digital', 'usb-et-manette', 'gachette-defectueuse', 'Gâchette défectueuse', 'gachette-defectueuse', 520),
  ('ps5-slim-digital', 'connexion', 'wi-fi-defectueux', 'Wi-Fi défectueux', 'wi-fi-defectueux', 530),
  ('ps5-slim-digital', 'connexion', 'bluetooth-defectueux', 'Bluetooth défectueux', 'bluetooth-defectueux', 540),
  ('ps5-slim-digital', 'connexion', 'wi-fi-non-detecte', 'Wi-Fi non détecté', 'wi-fi-non-detecte', 550),
  ('ps5-slim-digital', 'connexion', 'deconnexions-wi-fi', 'Déconnexions Wi-Fi', 'deconnexions-wi-fi', 560),
  ('ps5-slim-digital', 'connexion', 'probleme-de-connexion-internet', 'Problème de connexion Internet', 'probleme-de-connexion-internet', 570),
  ('ps5-slim-digital', 'connexion', 'ethernet-hs', 'Ethernet HS', 'ethernet-hs', 580),
  ('ps5-pro', 'image-et-hdmi', 'changement-du-port-hdmi', 'Changement du port HDMI', 'changement-du-port-hdmi', 10),
  ('ps5-pro', 'image-et-hdmi', 'port-hdmi-endommage', 'Port HDMI endommagé', 'port-hdmi-endommage', 20),
  ('ps5-pro', 'image-et-hdmi', 'aucun-signal-hdmi', 'Aucun signal HDMI', 'aucun-signal-hdmi', 30),
  ('ps5-pro', 'image-et-hdmi', 'ecran-noir-image-et-hdmi', 'Écran noir', 'ecran-noir-image-et-hdmi', 40),
  ('ps5-pro', 'image-et-hdmi', 'pas-dimage', 'Pas d’image', 'pas-dimage', 50),
  ('ps5-pro', 'image-et-hdmi', 'image-qui-coupe', 'Image qui coupe', 'image-qui-coupe', 60),
  ('ps5-pro', 'image-et-hdmi', 'image-instable', 'Image instable', 'image-instable', 70),
  ('ps5-pro', 'image-et-hdmi', 'image-deformee', 'Image déformée', 'image-deformee', 80),
  ('ps5-pro', 'image-et-hdmi', 'defauts-graphiques-artefacts', 'Défauts graphiques / artefacts', 'defauts-graphiques-artefacts', 90),
  ('ps5-pro', 'image-et-hdmi', 'probleme-de-resolution', 'Problème de résolution', 'probleme-de-resolution', 100),
  ('ps5-pro', 'image-et-hdmi', 'probleme-de-sortie-video', 'Problème de sortie vidéo', 'probleme-de-sortie-video', 110),
  ('ps5-pro', 'image-et-hdmi', 'pas-de-4k-120-hz', 'Pas de 4K / 120 Hz', 'pas-de-4k-120-hz', 120),
  ('ps5-pro', 'image-et-hdmi', 'hdr-indisponible', 'HDR indisponible', 'hdr-indisponible', 130),
  ('ps5-pro', 'allumage-et-alimentation', 'ps5-qui-ne-sallume-plus', 'PS5 qui ne s’allume plus', 'ps5-qui-ne-sallume-plus', 140),
  ('ps5-pro', 'allumage-et-alimentation', 'ps5-qui-seteint-immediatement', 'PS5 qui s’éteint immédiatement', 'ps5-qui-seteint-immediatement', 150),
  ('ps5-pro', 'allumage-et-alimentation', 'ps5-qui-seteint-toute-seule', 'PS5 qui s’éteint toute seule', 'ps5-qui-seteint-toute-seule', 160),
  ('ps5-pro', 'allumage-et-alimentation', 'voyant-blanc-clignotant', 'Voyant blanc clignotant', 'voyant-blanc-clignotant', 170),
  ('ps5-pro', 'allumage-et-alimentation', 'trois-bips-et-extinction', 'Trois bips puis extinction', 'trois-bips-et-extinction', 180),
  ('ps5-pro', 'allumage-et-alimentation', 'probleme-dalimentation', 'Problème d’alimentation', 'probleme-dalimentation', 190),
  ('ps5-pro', 'allumage-et-alimentation', 'bloc-dalimentation-defectueux', 'Bloc d’alimentation défectueux', 'bloc-dalimentation-defectueux', 200),
  ('ps5-pro', 'allumage-et-alimentation', 'connecteur-dalimentation-endommage', 'Connecteur d’alimentation endommagé', 'connecteur-dalimentation-endommage', 210),
  ('ps5-pro', 'allumage-et-alimentation', 'court-circuit', 'Court-circuit', 'court-circuit', 220),
  ('ps5-pro', 'allumage-et-alimentation', 'sortie-de-veille-impossible', 'Sortie de veille impossible', 'sortie-de-veille-impossible', 230),
  ('ps5-pro', 'lecteur-blu-ray', 'lecteur-amovible-non-reconnu', 'Lecteur amovible non reconnu', 'lecteur-amovible-non-reconnu', 240),
  ('ps5-pro', 'lecteur-blu-ray', 'connecteur-du-lecteur-amovible-endommage', 'Connecteur du lecteur amovible endommagé', 'connecteur-du-lecteur-amovible-endommage', 250),
  ('ps5-pro', 'ssd-et-stockage', 'ssd-interne-defectueux', 'SSD interne défectueux', 'ssd-interne-defectueux', 260),
  ('ps5-pro', 'ssd-et-stockage', 'ssd-non-reconnu', 'SSD non reconnu', 'ssd-non-reconnu', 270),
  ('ps5-pro', 'ssd-et-stockage', 'remplacement-du-ssd', 'Remplacement du SSD', 'remplacement-du-ssd', 280),
  ('ps5-pro', 'ssd-et-stockage', 'extension-ssd-m-2-non-reconnue', 'Extension SSD M.2 non reconnue', 'extension-ssd-m-2-non-reconnue', 290),
  ('ps5-pro', 'ssd-et-stockage', 'erreur-de-stockage-externe', 'Erreur de stockage externe', 'erreur-de-stockage-externe', 300),
  ('ps5-pro', 'ssd-et-stockage', 'console-bloquee-au-demarrage-ssd-et-stockage', 'Console bloquée au démarrage', 'console-bloquee-au-demarrage-ssd-et-stockage', 310),
  ('ps5-pro', 'systeme', 'erreur-du-logiciel-systeme', 'Erreur du logiciel système', 'erreur-du-logiciel-systeme', 320),
  ('ps5-pro', 'systeme', 'mise-a-jour-impossible', 'Mise à jour impossible', 'mise-a-jour-impossible', 330),
  ('ps5-pro', 'systeme', 'reinstallation-systeme-impossible', 'Réinstallation système impossible', 'reinstallation-systeme-impossible', 340),
  ('ps5-pro', 'systeme', 'boucle-du-mode-sans-echec', 'Boucle du mode sans échec', 'boucle-du-mode-sans-echec', 350),
  ('ps5-pro', 'systeme', 'base-de-donnees-corrompue', 'Base de données corrompue', 'base-de-donnees-corrompue', 360),
  ('ps5-pro', 'systeme', 'console-qui-se-fige', 'Console qui se fige', 'console-qui-se-fige', 370),
  ('ps5-pro', 'refroidissement', 'surchauffe', 'Surchauffe', 'surchauffe', 380),
  ('ps5-pro', 'refroidissement', 'ventilateur-bruyant', 'Ventilateur bruyant', 'ventilateur-bruyant', 390),
  ('ps5-pro', 'refroidissement', 'ventilateur-defectueux', 'Ventilateur défectueux', 'ventilateur-defectueux', 400),
  ('ps5-pro', 'refroidissement', 'console-qui-chauffe-anormalement', 'Console qui chauffe anormalement', 'console-qui-chauffe-anormalement', 410),
  ('ps5-pro', 'refroidissement', 'metal-liquide-degrade', 'Métal liquide dégradé', 'metal-liquide-degrade', 420),
  ('ps5-pro', 'refroidissement', 'nettoyage-et-depoussierage', 'Nettoyage et dépoussiérage', 'nettoyage-et-depoussierage', 430),
  ('ps5-pro', 'usb-et-manette', 'port-usb-defectueux', 'Port USB défectueux', 'port-usb-defectueux', 440),
  ('ps5-pro', 'usb-et-manette', 'port-usb-endommage', 'Port USB endommagé', 'port-usb-endommage', 450),
  ('ps5-pro', 'usb-et-manette', 'port-usb-c-endommage', 'Port USB-C endommagé', 'port-usb-c-endommage', 460),
  ('ps5-pro', 'usb-et-manette', 'manette-non-reconnue', 'Manette non reconnue', 'manette-non-reconnue', 470),
  ('ps5-pro', 'usb-et-manette', 'manette-qui-ne-se-connecte-pas', 'Manette qui ne se connecte pas', 'manette-qui-ne-se-connecte-pas', 480),
  ('ps5-pro', 'usb-et-manette', 'manette-qui-ne-charge-pas', 'Manette qui ne charge pas', 'manette-qui-ne-charge-pas', 490),
  ('ps5-pro', 'usb-et-manette', 'probleme-de-synchronisation', 'Problème de synchronisation', 'probleme-de-synchronisation', 500),
  ('ps5-pro', 'usb-et-manette', 'joystick-drift', 'Joystick drift', 'joystick-drift', 510),
  ('ps5-pro', 'usb-et-manette', 'gachette-defectueuse', 'Gâchette défectueuse', 'gachette-defectueuse', 520),
  ('ps5-pro', 'connexion', 'wi-fi-defectueux', 'Wi-Fi défectueux', 'wi-fi-defectueux', 530),
  ('ps5-pro', 'connexion', 'bluetooth-defectueux', 'Bluetooth défectueux', 'bluetooth-defectueux', 540),
  ('ps5-pro', 'connexion', 'wi-fi-non-detecte', 'Wi-Fi non détecté', 'wi-fi-non-detecte', 550),
  ('ps5-pro', 'connexion', 'deconnexions-wi-fi', 'Déconnexions Wi-Fi', 'deconnexions-wi-fi', 560),
  ('ps5-pro', 'connexion', 'probleme-de-connexion-internet', 'Problème de connexion Internet', 'probleme-de-connexion-internet', 570),
  ('ps5-pro', 'connexion', 'ethernet-hs', 'Ethernet HS', 'ethernet-hs', 580))
insert into public.repairs (model_id, fault_id, category_id, name, slug, price_cents, price_is_provisional, display_order, is_active)
select m.id, f.id, rc.id, s.name, s.slug, 0, true, s.display_order, true
  from source s
  join public.console_models m on m.slug = s.model_slug
  join public.faults f on f.slug = s.fault_slug
  join public.repair_categories rc on rc.slug = s.category_slug
on conflict (model_id, fault_id) do update
   set category_id = excluded.category_id,
       name = excluded.name,
       display_order = case when public.repairs.price_is_provisional then excluded.display_order else public.repairs.display_order end,
       updated_at = now();
