import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { ROUTES } from "@/config/site";

const OTP_TYPES = ["recovery", "magiclink", "signup", "email", "invite", "email_change"] as const;
type OtpType = (typeof OTP_TYPES)[number];

/**
 * Turns an auth link into a session:
 *  - PKCE flow (links generated by the SSR client): `?code=`
 *  - server-generated links (account created at checkout): `?token_hash=&type=`
 */
export async function GET(request: Request) {
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type");
  const rawNext = url.searchParams.get("next") ?? ROUTES.account;
  const next = rawNext.startsWith("/") && !rawNext.startsWith("//") ? rawNext : ROUTES.account;
  const supabase = await createSupabaseServerClient();
  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) return NextResponse.redirect(new URL(next, url.origin));
  } else if (tokenHash && type && (OTP_TYPES as readonly string[]).includes(type)) {
    const { error } = await supabase.auth.verifyOtp({ type: type as OtpType, token_hash: tokenHash });
    if (!error) return NextResponse.redirect(new URL(next, url.origin));
  }
  return NextResponse.redirect(new URL(`${ROUTES.login}?error=lien-invalide`, url.origin));
}
