#!/usr/bin/env python3
"""
Generates types/database.ts (same shape as `supabase gen types typescript`)
from a plain PostgreSQL connection. Used when the Supabase CLI cannot run
(no Docker). Usage:
  python3 scripts/gen-db-types.py "postgresql://postgres:postgres@localhost:5432/console_repair_test" > types/database.ts
"""
import subprocess, sys, json

DB_URL = sys.argv[1] if len(sys.argv) > 1 else "postgresql://postgres:postgres@localhost:5432/console_repair_test"

def q(sql):
    out = subprocess.run(["psql", DB_URL, "-At", "-F", "\t", "-c", sql], capture_output=True, text=True, check=True).stdout
    return [line.split("\t") for line in out.strip().split("\n") if line]

SCALAR = {
    "uuid": "string", "text": "string", "citext": "string", "character": "string", "character varying": "string",
    "bpchar": "string", "date": "string", "timestamp with time zone": "string", "timestamp without time zone": "string",
    "integer": "number", "bigint": "number", "smallint": "number", "numeric": "number", "double precision": "number", "real": "number",
    "boolean": "boolean", "jsonb": "Json", "json": "Json", "inet": "unknown", "bytea": "string",
}

enums = {}
for name, labels in q("select t.typname, string_agg(e.enumlabel, ',' order by e.enumsortorder) from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' group by t.typname order by t.typname"):
    enums[name] = labels.split(",")

def ts_type(data_type, udt_name, is_array):
    if data_type == "ARRAY":
        base = udt_name.lstrip("_")
        inner = enums_ref(base) if base in enums else SCALAR.get({"int4": "integer", "int8": "bigint", "bool": "boolean", "varchar": "text"}.get(base, base), "string")
        return f"{inner}[]"
    if data_type == "USER-DEFINED":
        if udt_name in enums:
            return enums_ref(udt_name)
        if udt_name == "citext":
            return "string"
        return "unknown"
    return SCALAR.get(data_type, "unknown")

def enums_ref(name):
    return f'Database["public"]["Enums"]["{name}"]'

def columns(rel, kind):
    rows = q(f"""select column_name, data_type, udt_name, is_nullable, column_default is not null, is_identity
                 from information_schema.columns where table_schema='public' and table_name='{rel}' order by ordinal_position""")
    return rows

fks = q("""select tc.table_name, tc.constraint_name, kcu.column_name, ccu.table_name, ccu.column_name,
                  exists (select 1 from pg_constraint c join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any(c.conkey)
                           where c.contype in ('u','p') and c.conrelid = (quote_ident(tc.table_schema)||'.'||quote_ident(tc.table_name))::regclass
                             and array_length(c.conkey,1) = 1 and a.attname = kcu.column_name) as one_to_one
             from information_schema.table_constraints tc
             join information_schema.key_column_usage kcu on kcu.constraint_name = tc.constraint_name and kcu.table_schema = tc.table_schema
             join information_schema.constraint_column_usage ccu on ccu.constraint_name = tc.constraint_name and ccu.table_schema = tc.table_schema
             where tc.constraint_type = 'FOREIGN KEY' and tc.table_schema = 'public'
             order by tc.table_name, tc.constraint_name""")

def relationships(table):
    out = []
    for t, cname, col, rtable, rcol, one in fks:
        if t != table: continue
        out.append(f"""          {{
            foreignKeyName: "{cname}";
            columns: ["{col}"];
            isOneToOne: {"true" if one == "t" else "false"};
            referencedRelation: "{rtable}";
            referencedColumns: ["{rcol}"];
          }}""")
    if not out:
        return "        Relationships: [];"
    return "        Relationships: [\n" + ",\n".join(out) + "\n        ];"

tables = [r[0] for r in q("select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by table_name")]
views = [r[0] for r in q("select table_name from information_schema.views where table_schema='public' order by table_name")]
functions = q("""select p.proname, pg_get_function_arguments(p.oid), pg_get_function_result(p.oid)
                 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname='public' and p.prokind='f'
                   and p.prorettype <> 'trigger'::regtype
                   and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
                 order by p.proname""")

lines = []
w = lines.append
w("// AUTO-GENERATED by scripts/gen-db-types.py — do not edit by hand.")
w("// Regenerate after every migration: npm run db:types (Supabase CLI) or the script above.")
w("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];")
w("")
w("export type Database = {")
w("  public: {")
w("    Tables: {")
for t in tables:
    cols = columns(t, "table")
    w(f"      {t}: {{")
    w("        Row: {")
    for name, dt, udt, nullable, has_default, ident in cols:
        typ = ts_type(dt, udt, False)
        w(f"          {name}: {typ}{' | null' if nullable == 'YES' else ''};")
    w("        };")
    w("        Insert: {")
    for name, dt, udt, nullable, has_default, ident in cols:
        typ = ts_type(dt, udt, False)
        optional = nullable == "YES" or has_default == "t"
        w(f"          {name}{'?' if optional else ''}: {typ}{' | null' if nullable == 'YES' else ''};")
    w("        };")
    w("        Update: {")
    for name, dt, udt, nullable, has_default, ident in cols:
        typ = ts_type(dt, udt, False)
        w(f"          {name}?: {typ}{' | null' if nullable == 'YES' else ''};")
    w("        };")
    w(relationships(t))
    w("      };")
w("    };")
w("    Views: {")
for v in views:
    cols = columns(v, "view")
    w(f"      {v}: {{")
    w("        Row: {")
    for name, dt, udt, nullable, has_default, ident in cols:
        typ = ts_type(dt, udt, False)
        w(f"          {name}: {typ} | null;")
    w("        };")
    w("        Relationships: [];")
    w("      };")
w("    };")
w("    Functions: {")
def map_sql_type(t):
    t = t.strip()
    if t.startswith("public."):
        t = t[len("public."):]
    if t in enums: return enums_ref(t)
    if t in tables: return f'Database["public"]["Tables"]["{t}"]["Row"]'
    return SCALAR.get(t, {"int4":"number","int8":"number","bool":"boolean"}.get(t, "unknown"))
for name, args, result in functions:
    w(f"      {name}: {{")
    if args.strip():
        w("        Args: {")
        for a in args.split(","):
            parts = a.strip().split(" ")
            aname = parts[0]
            has_default = "DEFAULT" in a
            atype = " ".join(parts[1:]).split(" DEFAULT")[0].strip()
            w(f"          {aname}{'?' if has_default else ''}: {map_sql_type(atype)};")
        w("        };")
    else:
        w("        Args: Record<PropertyKey, never>;")
    w(f"        Returns: {map_sql_type(result)};")
    w("      };")
w("    };")
w("    Enums: {")
for name, labels in enums.items():
    w(f"      {name}: {' | '.join(json.dumps(l) for l in labels)};")
w("    };")
w("    CompositeTypes: Record<string, never>;")
w("  };")
w("};")
w("")
w('export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];')
w('export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];')
w('export type TablesUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"];')
w('export type Views<T extends keyof Database["public"]["Views"]> = Database["public"]["Views"][T]["Row"];')
w('export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];')
print("\n".join(lines))
